/* API Interceptor (c) 2024 Dominik Witczak
 *
 * This code is licensed under MIT license (see LICENSE.txt for details)
 */
#ifndef AI_TYPES_TYPEDEFS_H
#define AI_TYPES_TYPEDEFS_H

namespace OpenGL
{
    /* GL_EXT_texture_object */
    typedef GLboolean (AI_APIENTRY* PFNGLARETEXTURESRESIDENTEXTPROC)(GLsizei         n,
                                                                     const GLuint*   textures,
                                                                     GLboolean*      residences);
    typedef void      (AI_APIENTRY* PFNGLPRIORITIZETEXTURESEXTPROC) (GLsizei         n,
                                                                     const GLuint*   textures,
                                                                     const GLclampf* priorities);
}

/* Core 1.1 compat profile */
typedef void           (AI_APIENTRY* PFNGLACCUMPROC)                 (GLenum op, GLfloat value);
typedef void           (AI_APIENTRY* PFNGLALPHAFUNCPROC)             (GLenum func, GLclampf ref);
typedef GLboolean      (AI_APIENTRY* PFNGLARETEXTURESRESIDENTPROC)   (GLsizei n, const GLuint *textures, GLboolean *residences);
typedef void           (AI_APIENTRY* PFNGLARRAYELEMENTPROC)          (GLint i);
typedef void           (AI_APIENTRY* PFNGLBEGINPROC)                 (GLenum mode);
typedef void           (AI_APIENTRY* PFNGLBINDTEXTUREPROC)           (GLenum target, GLuint texture);
typedef void           (AI_APIENTRY* PFNGLBITMAPPROC)                (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap);
typedef void           (AI_APIENTRY* PFNGLBLENDFUNCPROC)             (GLenum sfactor, GLenum dfactor);
typedef void           (AI_APIENTRY* PFNGLCALLLISTPROC)              (GLuint list);
typedef void           (AI_APIENTRY* PFNGLCALLLISTSPROC)             (GLsizei n, GLenum type, const GLvoid *lists);
typedef void           (AI_APIENTRY* PFNGLCLEARPROC)                 (GLbitfield mask);
typedef void           (AI_APIENTRY* PFNGLCLEARACCUMPROC)            (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
typedef void           (AI_APIENTRY* PFNGLCLEARCOLORPROC)            (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
typedef void           (AI_APIENTRY* PFNGLCLEARDEPTHPROC)            (GLclampd depth);
typedef void           (AI_APIENTRY* PFNGLCLEARINDEXPROC)            (GLfloat c);
typedef void           (AI_APIENTRY* PFNGLCLEARSTENCILPROC)          (GLint s);
typedef void           (AI_APIENTRY* PFNGLCLIPPLANEPROC)             (GLenum plane, const GLdouble *equation);
typedef void           (AI_APIENTRY* PFNGLCOLOR3BPROC)               (GLbyte red, GLbyte green, GLbyte blue);
typedef void           (AI_APIENTRY* PFNGLCOLOR3BVPROC)              (const GLbyte *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR3DPROC)               (GLdouble red, GLdouble green, GLdouble blue);
typedef void           (AI_APIENTRY* PFNGLCOLOR3DVPROC)              (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR3FPROC)               (GLfloat red, GLfloat green, GLfloat blue);
typedef void           (AI_APIENTRY* PFNGLCOLOR3FVPROC)              (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR3IPROC)               (GLint red, GLint green, GLint blue);
typedef void           (AI_APIENTRY* PFNGLCOLOR3IVPROC)              (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR3SPROC)               (GLshort red, GLshort green, GLshort blue);
typedef void           (AI_APIENTRY* PFNGLCOLOR3SVPROC)              (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR3UBPROC)              (GLubyte red, GLubyte green, GLubyte blue);
typedef void           (AI_APIENTRY* PFNGLCOLOR3UBVPROC)             (const GLubyte *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR3UIPROC)              (GLuint red, GLuint green, GLuint blue);
typedef void           (AI_APIENTRY* PFNGLCOLOR3UIVPROC)             (const GLuint *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR3USPROC)              (GLushort red, GLushort green, GLushort blue);
typedef void           (AI_APIENTRY* PFNGLCOLOR3USVPROC)             (const GLushort *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR4BPROC)               (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha);
typedef void           (AI_APIENTRY* PFNGLCOLOR4BVPROC)              (const GLbyte *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR4DPROC)               (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha);
typedef void           (AI_APIENTRY* PFNGLCOLOR4DVPROC)              (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR4FPROC)               (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
typedef void           (AI_APIENTRY* PFNGLCOLOR4FVPROC)              (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR4IPROC)               (GLint red, GLint green, GLint blue, GLint alpha);
typedef void           (AI_APIENTRY* PFNGLCOLOR4IVPROC)              (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR4SPROC)               (GLshort red, GLshort green, GLshort blue, GLshort alpha);
typedef void           (AI_APIENTRY* PFNGLCOLOR4SVPROC)              (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR4UBPROC)              (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
typedef void           (AI_APIENTRY* PFNGLCOLOR4UBVPROC)             (const GLubyte *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR4UIPROC)              (GLuint red, GLuint green, GLuint blue, GLuint alpha);
typedef void           (AI_APIENTRY* PFNGLCOLOR4UIVPROC)             (const GLuint *v);
typedef void           (AI_APIENTRY* PFNGLCOLOR4USPROC)              (GLushort red, GLushort green, GLushort blue, GLushort alpha);
typedef void           (AI_APIENTRY* PFNGLCOLOR4USVPROC)             (const GLushort *v);
typedef void           (AI_APIENTRY* PFNGLCOLORMASKPROC)             (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
typedef void           (AI_APIENTRY* PFNGLCOLORMATERIALPROC)         (GLenum face, GLenum mode);
typedef void           (AI_APIENTRY* PFNGLCOLORPOINTERPROC)          (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void           (AI_APIENTRY* PFNGLCOPYPIXELSPROC)            (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
typedef void           (AI_APIENTRY* PFNGLCOPYTEXIMAGE1DPROC)        (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLint border);
typedef void           (AI_APIENTRY* PFNGLCOPYTEXIMAGE2DPROC)        (GLenum target, GLint level, GLenum internalFormat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
typedef void           (AI_APIENTRY* PFNGLCOPYTEXSUBIMAGE1DPROC)     (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width);
typedef void           (AI_APIENTRY* PFNGLCOPYTEXSUBIMAGE2DPROC)     (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
typedef void           (AI_APIENTRY* PFNGLCULLFACEPROC)              (GLenum mode);
typedef void           (AI_APIENTRY* PFNGLDELETELISTSPROC)           (GLuint list, GLsizei range);
typedef void           (AI_APIENTRY* PFNGLDELETETEXTURESPROC)        (GLsizei n, const GLuint *textures);
typedef void           (AI_APIENTRY* PFNGLDEPTHFUNCPROC)             (GLenum func);
typedef void           (AI_APIENTRY* PFNGLDEPTHMASKPROC)             (GLboolean flag);
typedef void           (AI_APIENTRY* PFNGLDEPTHRANGEPROC)            (GLclampd zNear, GLclampd zFar);
typedef void           (AI_APIENTRY* PFNGLDISABLEPROC)               (GLenum cap);
typedef void           (AI_APIENTRY* PFNGLDISABLECLIENTSTATEPROC)    (GLenum array);
typedef void           (AI_APIENTRY* PFNGLDRAWARRAYSPROC)            (GLenum mode, GLint first, GLsizei count);
typedef void           (AI_APIENTRY* PFNGLDRAWBUFFERPROC)            (GLenum mode);
typedef void           (AI_APIENTRY* PFNGLDRAWELEMENTSPROC)          (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices);
typedef void           (AI_APIENTRY* PFNGLDRAWPIXELSPROC)            (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
typedef void           (AI_APIENTRY* PFNGLEDGEFLAGPROC)              (GLboolean flag);
typedef void           (AI_APIENTRY* PFNGLEDGEFLAGPOINTERPROC)       (GLsizei stride, const GLvoid *pointer);
typedef void           (AI_APIENTRY* PFNGLEDGEFLAGVPROC)             (const GLboolean *flag);
typedef void           (AI_APIENTRY* PFNGLENABLEPROC)                (GLenum cap);
typedef void           (AI_APIENTRY* PFNGLENABLECLIENTSTATEPROC)     (GLenum array);
typedef void           (AI_APIENTRY* PFNGLENDPROC)                   ();
typedef void           (AI_APIENTRY* PFNGLENDLISTPROC)               ();
typedef void           (AI_APIENTRY* PFNGLEVALCOORD1DPROC)           (GLdouble u);
typedef void           (AI_APIENTRY* PFNGLEVALCOORD1DVPROC)          (const GLdouble *u);
typedef void           (AI_APIENTRY* PFNGLEVALCOORD1FPROC)           (GLfloat u);
typedef void           (AI_APIENTRY* PFNGLEVALCOORD1FVPROC)          (const GLfloat *u);
typedef void           (AI_APIENTRY* PFNGLEVALCOORD2DPROC)           (GLdouble u, GLdouble v);
typedef void           (AI_APIENTRY* PFNGLEVALCOORD2DVPROC)          (const GLdouble *u);
typedef void           (AI_APIENTRY* PFNGLEVALCOORD2FPROC)           (GLfloat u, GLfloat v);
typedef void           (AI_APIENTRY* PFNGLEVALCOORD2FVPROC)          (const GLfloat *u);
typedef void           (AI_APIENTRY* PFNGLEVALMESH1PROC)             (GLenum mode, GLint i1, GLint i2);
typedef void           (AI_APIENTRY* PFNGLEVALMESH2PROC)             (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2);
typedef void           (AI_APIENTRY* PFNGLEVALPOINT1PROC)            (GLint i);
typedef void           (AI_APIENTRY* PFNGLEVALPOINT2PROC)            (GLint i, GLint j);
typedef void           (AI_APIENTRY* PFNGLFEEDBACKBUFFERPROC)        (GLsizei size, GLenum type, GLfloat *buffer);
typedef void           (AI_APIENTRY* PFNGLFINISHPROC)                ();
typedef void           (AI_APIENTRY* PFNGLFLUSHPROC)                 ();
typedef void           (AI_APIENTRY* PFNGLFOGFPROC)                  (GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLFOGFVPROC)                 (GLenum pname, const GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLFOGIPROC)                  (GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLFOGIVPROC)                 (GLenum pname, const GLint *params);
typedef void           (AI_APIENTRY* PFNGLFRONTFACEPROC)             (GLenum mode);
typedef void           (AI_APIENTRY* PFNGLFRUSTUMPROC)               (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
typedef GLuint         (AI_APIENTRY* PFNGLGENLISTSPROC)              (GLsizei range);
typedef void           (AI_APIENTRY* PFNGLGENTEXTURESPROC)           (GLsizei n, GLuint *textures);
typedef void           (AI_APIENTRY* PFNGLGETBOOLEANVPROC)           (GLenum pname, GLboolean *params);
typedef void           (AI_APIENTRY* PFNGLGETCLIPPLANEPROC)          (GLenum plane, GLdouble *equation);
typedef void           (AI_APIENTRY* PFNGLGETDOUBLEVPROC)            (GLenum pname, GLdouble *params);
typedef GLenum         (AI_APIENTRY* PFNGLGETERRORPROC)              ();
typedef void           (AI_APIENTRY* PFNGLGETFLOATVPROC)             (GLenum pname, GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLGETINTEGERVPROC)           (GLenum pname, GLint *params);
typedef void           (AI_APIENTRY* PFNGLGETLIGHTFVPROC)            (GLenum light, GLenum pname, GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLGETLIGHTIVPROC)            (GLenum light, GLenum pname, GLint *params);
typedef void           (AI_APIENTRY* PFNGLGETMAPDVPROC)              (GLenum target, GLenum query, GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLGETMAPFVPROC)              (GLenum target, GLenum query, GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLGETMAPIVPROC)              (GLenum target, GLenum query, GLint *v);
typedef void           (AI_APIENTRY* PFNGLGETMATERIALFVPROC)         (GLenum face, GLenum pname, GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLGETMATERIALIVPROC)         (GLenum face, GLenum pname, GLint *params);
typedef void           (AI_APIENTRY* PFNGLGETPIXELMAPFVPROC)         (GLenum map, GLfloat *values);
typedef void           (AI_APIENTRY* PFNGLGETPIXELMAPUIVPROC)        (GLenum map, GLuint *values);
typedef void           (AI_APIENTRY* PFNGLGETPIXELMAPUSVPROC)        (GLenum map, GLushort *values);
typedef void           (AI_APIENTRY* PFNGLGETPOINTERVPROC)           (GLenum pname, GLvoid* *params);
typedef void           (AI_APIENTRY* PFNGLGETPOLYGONSTIPPLEPROC)     (GLubyte *mask);
typedef const GLubyte* (AI_APIENTRY* PFNGLGETSTRINGPROC)             (GLenum name);
typedef void           (AI_APIENTRY* PFNGLGETTEXENVFVPROC)           (GLenum target, GLenum pname, GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLGETTEXENVIVPROC)           (GLenum target, GLenum pname, GLint *params);
typedef void           (AI_APIENTRY* PFNGLGETTEXGENDVPROC)           (GLenum coord, GLenum pname, GLdouble *params);
typedef void           (AI_APIENTRY* PFNGLGETTEXGENFVPROC)           (GLenum coord, GLenum pname, GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLGETTEXGENIVPROC)           (GLenum coord, GLenum pname, GLint *params);
typedef void           (AI_APIENTRY* PFNGLGETTEXIMAGEPROC)           (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels);
typedef void           (AI_APIENTRY* PFNGLGETTEXLEVELPARAMETERFVPROC)(GLenum target, GLint level, GLenum pname, GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLGETTEXLEVELPARAMETERIVPROC)(GLenum target, GLint level, GLenum pname, GLint *params);
typedef void           (AI_APIENTRY* PFNGLGETTEXPARAMETERFVPROC)     (GLenum target, GLenum pname, GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLGETTEXPARAMETERIVPROC)     (GLenum target, GLenum pname, GLint *params);
typedef void           (AI_APIENTRY* PFNGLHINTPROC)                  (GLenum target, GLenum mode);
typedef void           (AI_APIENTRY* PFNGLINDEXMASKPROC)             (GLuint mask);
typedef void           (AI_APIENTRY* PFNGLINDEXPOINTERPROC)          (GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void           (AI_APIENTRY* PFNGLINDEXDPROC)                (GLdouble c);
typedef void           (AI_APIENTRY* PFNGLINDEXDVPROC)               (const GLdouble *c);
typedef void           (AI_APIENTRY* PFNGLINDEXFPROC)                (GLfloat c);
typedef void           (AI_APIENTRY* PFNGLINDEXFVPROC)               (const GLfloat *c);
typedef void           (AI_APIENTRY* PFNGLINDEXIPROC)                (GLint c);
typedef void           (AI_APIENTRY* PFNGLINDEXIVPROC)               (const GLint *c);
typedef void           (AI_APIENTRY* PFNGLINDEXSPROC)                (GLshort c);
typedef void           (AI_APIENTRY* PFNGLINDEXSVPROC)               (const GLshort *c);
typedef void           (AI_APIENTRY* PFNGLINDEXUBPROC)               (GLubyte c);
typedef void           (AI_APIENTRY* PFNGLINDEXUBVPROC)              (const GLubyte *c);
typedef void           (AI_APIENTRY* PFNGLINITNAMESPROC)             ();
typedef void           (AI_APIENTRY* PFNGLINTERLEAVEDARRAYSPROC)     (GLenum format, GLsizei stride, const GLvoid *pointer);
typedef GLboolean      (AI_APIENTRY* PFNGLISENABLEDPROC)             (GLenum cap);
typedef GLboolean      (AI_APIENTRY* PFNGLISLISTPROC)                (GLuint list);
typedef GLboolean      (AI_APIENTRY* PFNGLISTEXTUREPROC)             (GLuint texture);
typedef void           (AI_APIENTRY* PFNGLLIGHTMODELFPROC)           (GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLLIGHTMODELFVPROC)          (GLenum pname, const GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLLIGHTMODELIPROC)           (GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLLIGHTMODELIVPROC)          (GLenum pname, const GLint *params);
typedef void           (AI_APIENTRY* PFNGLLIGHTFPROC)                (GLenum light, GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLLIGHTFVPROC)               (GLenum light, GLenum pname, const GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLLIGHTIPROC)                (GLenum light, GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLLIGHTIVPROC)               (GLenum light, GLenum pname, const GLint *params);
typedef void           (AI_APIENTRY* PFNGLLINESTIPPLEPROC)           (GLint factor, GLushort pattern);
typedef void           (AI_APIENTRY* PFNGLLINEWIDTHPROC)             (GLfloat width);
typedef void           (AI_APIENTRY* PFNGLLISTBASEPROC)              (GLuint base);
typedef void           (AI_APIENTRY* PFNGLLOADIDENTITYPROC)          ();
typedef void           (AI_APIENTRY* PFNGLLOADMATRIXDPROC)           (const GLdouble *m);
typedef void           (AI_APIENTRY* PFNGLLOADMATRIXFPROC)           (const GLfloat *m);
typedef void           (AI_APIENTRY* PFNGLLOADNAMEPROC)              (GLuint name);
typedef void           (AI_APIENTRY* PFNGLLOGICOPPROC)               (GLenum opcode);
typedef void           (AI_APIENTRY* PFNGLMAP1DPROC)                 (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points);
typedef void           (AI_APIENTRY* PFNGLMAP1FPROC)                 (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points);
typedef void           (AI_APIENTRY* PFNGLMAP2DPROC)                 (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points);
typedef void           (AI_APIENTRY* PFNGLMAP2FPROC)                 (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points);
typedef void           (AI_APIENTRY* PFNGLMAPGRID1DPROC)             (GLint un, GLdouble u1, GLdouble u2);
typedef void           (AI_APIENTRY* PFNGLMAPGRID1FPROC)             (GLint un, GLfloat u1, GLfloat u2);
typedef void           (AI_APIENTRY* PFNGLMAPGRID2DPROC)             (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2);
typedef void           (AI_APIENTRY* PFNGLMAPGRID2FPROC)             (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2);
typedef void           (AI_APIENTRY* PFNGLMATERIALFPROC)             (GLenum face, GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLMATERIALFVPROC)            (GLenum face, GLenum pname, const GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLMATERIALIPROC)             (GLenum face, GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLMATERIALIVPROC)            (GLenum face, GLenum pname, const GLint *params);
typedef void           (AI_APIENTRY* PFNGLMATRIXMODEPROC)            (GLenum mode);
typedef void           (AI_APIENTRY* PFNGLMULTMATRIXDPROC)           (const GLdouble *m);
typedef void           (AI_APIENTRY* PFNGLMULTMATRIXFPROC)           (const GLfloat *m);
typedef void           (AI_APIENTRY* PFNGLNEWLISTPROC)               (GLuint list, GLenum mode);
typedef void           (AI_APIENTRY* PFNGLNORMAL3BPROC)              (GLbyte nx, GLbyte ny, GLbyte nz);
typedef void           (AI_APIENTRY* PFNGLNORMAL3BVPROC)             (const GLbyte *v);
typedef void           (AI_APIENTRY* PFNGLNORMAL3DPROC)              (GLdouble nx, GLdouble ny, GLdouble nz);
typedef void           (AI_APIENTRY* PFNGLNORMAL3DVPROC)             (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLNORMAL3FPROC)              (GLfloat nx, GLfloat ny, GLfloat nz);
typedef void           (AI_APIENTRY* PFNGLNORMAL3FVPROC)             (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLNORMAL3IPROC)              (GLint nx, GLint ny, GLint nz);
typedef void           (AI_APIENTRY* PFNGLNORMAL3IVPROC)             (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLNORMAL3SPROC)              (GLshort nx, GLshort ny, GLshort nz);
typedef void           (AI_APIENTRY* PFNGLNORMAL3SVPROC)             (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLNORMALPOINTERPROC)         (GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void           (AI_APIENTRY* PFNGLORTHOPROC)                 (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble zNear, GLdouble zFar);
typedef void           (AI_APIENTRY* PFNGLPASSTHROUGHPROC)           (GLfloat token);
typedef void           (AI_APIENTRY* PFNGLPIXELMAPFVPROC)            (GLenum map, GLsizei mapsize, const GLfloat *values);
typedef void           (AI_APIENTRY* PFNGLPIXELMAPUIVPROC)           (GLenum map, GLsizei mapsize, const GLuint *values);
typedef void           (AI_APIENTRY* PFNGLPIXELMAPUSVPROC)           (GLenum map, GLsizei mapsize, const GLushort *values);
typedef void           (AI_APIENTRY* PFNGLPIXELSTOREFPROC)           (GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLPIXELSTOREIPROC)           (GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLPIXELTRANSFERFPROC)        (GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLPIXELTRANSFERIPROC)        (GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLPIXELZOOMPROC)             (GLfloat xfactor, GLfloat yfactor);
typedef void           (AI_APIENTRY* PFNGLPOINTSIZEPROC)             (GLfloat size);
typedef void           (AI_APIENTRY* PFNGLPOLYGONMODEPROC)           (GLenum face, GLenum mode);
typedef void           (AI_APIENTRY* PFNGLPOLYGONOFFSETPROC)         (GLfloat factor, GLfloat units);
typedef void           (AI_APIENTRY* PFNGLPOLYGONSTIPPLEPROC)        (const GLubyte *mask);
typedef void           (AI_APIENTRY* PFNGLPOPATTRIBPROC)             ();
typedef void           (AI_APIENTRY* PFNGLPOPCLIENTATTRIBPROC)       ();
typedef void           (AI_APIENTRY* PFNGLPOPMATRIXPROC)             ();
typedef void           (AI_APIENTRY* PFNGLPOPNAMEPROC)               ();
typedef void           (AI_APIENTRY* PFNGLPRIORITIZETEXTURESPROC)    (GLsizei n, const GLuint *textures, const GLclampf *priorities);
typedef void           (AI_APIENTRY* PFNGLPUSHATTRIBPROC)            (GLbitfield mask);
typedef void           (AI_APIENTRY* PFNGLPUSHCLIENTATTRIBPROC)      (GLbitfield mask);
typedef void           (AI_APIENTRY* PFNGLPUSHMATRIXPROC)            ();
typedef void           (AI_APIENTRY* PFNGLPUSHNAMEPROC)              (GLuint name);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS2DPROC)           (GLdouble x, GLdouble y);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS2DVPROC)          (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS2FPROC)           (GLfloat x, GLfloat y);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS2FVPROC)          (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS2IPROC)           (GLint x, GLint y);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS2IVPROC)          (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS2SPROC)           (GLshort x, GLshort y);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS2SVPROC)          (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS3DPROC)           (GLdouble x, GLdouble y, GLdouble z);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS3DVPROC)          (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS3FPROC)           (GLfloat x, GLfloat y, GLfloat z);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS3FVPROC)          (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS3IPROC)           (GLint x, GLint y, GLint z);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS3IVPROC)          (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS3SPROC)           (GLshort x, GLshort y, GLshort z);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS3SVPROC)          (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS4DPROC)           (GLdouble x, GLdouble y, GLdouble z, GLdouble w);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS4DVPROC)          (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS4FPROC)           (GLfloat x, GLfloat y, GLfloat z, GLfloat w);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS4FVPROC)          (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS4IPROC)           (GLint x, GLint y, GLint z, GLint w);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS4IVPROC)          (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS4SPROC)           (GLshort x, GLshort y, GLshort z, GLshort w);
typedef void           (AI_APIENTRY* PFNGLRASTERPOS4SVPROC)          (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLREADBUFFERPROC)            (GLenum mode);
typedef void           (AI_APIENTRY* PFNGLREADPIXELSPROC)            (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels);
typedef void           (AI_APIENTRY* PFNGLRECTDPROC)                 (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2);
typedef void           (AI_APIENTRY* PFNGLRECTDVPROC)                (const GLdouble *v1, const GLdouble *v2);
typedef void           (AI_APIENTRY* PFNGLRECTFPROC)                 (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2);
typedef void           (AI_APIENTRY* PFNGLRECTFVPROC)                (const GLfloat *v1, const GLfloat *v2);
typedef void           (AI_APIENTRY* PFNGLRECTIPROC)                 (GLint x1, GLint y1, GLint x2, GLint y2);
typedef void           (AI_APIENTRY* PFNGLRECTIVPROC)                (const GLint *v1, const GLint *v2);
typedef void           (AI_APIENTRY* PFNGLRECTSPROC)                 (GLshort x1, GLshort y1, GLshort x2, GLshort y2);
typedef void           (AI_APIENTRY* PFNGLRECTSVPROC)                (const GLshort *v1, const GLshort *v2);
typedef GLint          (AI_APIENTRY* PFNGLRENDERMODEPROC)            (GLenum mode);
typedef void           (AI_APIENTRY* PFNGLROTATEDPROC)               (GLdouble angle, GLdouble x, GLdouble y, GLdouble z);
typedef void           (AI_APIENTRY* PFNGLROTATEFPROC)               (GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
typedef void           (AI_APIENTRY* PFNGLSCALEDPROC)                (GLdouble x, GLdouble y, GLdouble z);
typedef void           (AI_APIENTRY* PFNGLSCALEFPROC)                (GLfloat x, GLfloat y, GLfloat z);
typedef void           (AI_APIENTRY* PFNGLSCISSORPROC)               (GLint x, GLint y, GLsizei width, GLsizei height);
typedef void           (AI_APIENTRY* PFNGLSELECTBUFFERPROC)          (GLsizei size, GLuint *buffer);
typedef void           (AI_APIENTRY* PFNGLSHADEMODELPROC)            (GLenum mode);
typedef void           (AI_APIENTRY* PFNGLSTENCILFUNCPROC)           (GLenum func, GLint ref, GLuint mask);
typedef void           (AI_APIENTRY* PFNGLSTENCILMASKPROC)           (GLuint mask);
typedef void           (AI_APIENTRY* PFNGLSTENCILOPPROC)             (GLenum fail, GLenum zfail, GLenum zpass);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD1DPROC)            (GLdouble s);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD1DVPROC)           (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD1FPROC)            (GLfloat s);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD1FVPROC)           (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD1IPROC)            (GLint s);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD1IVPROC)           (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD1SPROC)            (GLshort s);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD1SVPROC)           (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD2DPROC)            (GLdouble s, GLdouble t);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD2DVPROC)           (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD2FPROC)            (GLfloat s, GLfloat t);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD2FVPROC)           (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD2IPROC)            (GLint s, GLint t);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD2IVPROC)           (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD2SPROC)            (GLshort s, GLshort t);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD2SVPROC)           (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD3DPROC)            (GLdouble s, GLdouble t, GLdouble r);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD3DVPROC)           (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD3FPROC)            (GLfloat s, GLfloat t, GLfloat r);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD3FVPROC)           (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD3IPROC)            (GLint s, GLint t, GLint r);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD3IVPROC)           (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD3SPROC)            (GLshort s, GLshort t, GLshort r);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD3SVPROC)           (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD4DPROC)            (GLdouble s, GLdouble t, GLdouble r, GLdouble q);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD4DVPROC)           (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD4FPROC)            (GLfloat s, GLfloat t, GLfloat r, GLfloat q);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD4FVPROC)           (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD4IPROC)            (GLint s, GLint t, GLint r, GLint q);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD4IVPROC)           (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD4SPROC)            (GLshort s, GLshort t, GLshort r, GLshort q);
typedef void           (AI_APIENTRY* PFNGLTEXCOORD4SVPROC)           (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLTEXCOORDPOINTERPROC)       (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void           (AI_APIENTRY* PFNGLTEXENVFPROC)               (GLenum target, GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLTEXENVFVPROC)              (GLenum target, GLenum pname, const GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLTEXENVIPROC)               (GLenum target, GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLTEXENVIVPROC)              (GLenum target, GLenum pname, const GLint *params);
typedef void           (AI_APIENTRY* PFNGLTEXGENDPROC)               (GLenum coord, GLenum pname, GLdouble param);
typedef void           (AI_APIENTRY* PFNGLTEXGENDVPROC)              (GLenum coord, GLenum pname, const GLdouble *params);
typedef void           (AI_APIENTRY* PFNGLTEXGENFPROC)               (GLenum coord, GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLTEXGENFVPROC)              (GLenum coord, GLenum pname, const GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLTEXGENIPROC)               (GLenum coord, GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLTEXGENIVPROC)              (GLenum coord, GLenum pname, const GLint *params);
typedef void           (AI_APIENTRY* PFNGLTEXIMAGE1DPROC)            (GLenum target, GLint level, GLint internalformat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
typedef void           (AI_APIENTRY* PFNGLTEXIMAGE2DPROC)            (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
typedef void           (AI_APIENTRY* PFNGLTEXPARAMETERFPROC)         (GLenum target, GLenum pname, GLfloat param);
typedef void           (AI_APIENTRY* PFNGLTEXPARAMETERFVPROC)        (GLenum target, GLenum pname, const GLfloat *params);
typedef void           (AI_APIENTRY* PFNGLTEXPARAMETERIPROC)         (GLenum target, GLenum pname, GLint param);
typedef void           (AI_APIENTRY* PFNGLTEXPARAMETERIVPROC)        (GLenum target, GLenum pname, const GLint *params);
typedef void           (AI_APIENTRY* PFNGLTEXSUBIMAGE1DPROC)         (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels);
typedef void           (AI_APIENTRY* PFNGLTEXSUBIMAGE2DPROC)         (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels);
typedef void           (AI_APIENTRY* PFNGLTRANSLATEDPROC)            (GLdouble x, GLdouble y, GLdouble z);
typedef void           (AI_APIENTRY* PFNGLTRANSLATEFPROC)            (GLfloat x, GLfloat y, GLfloat z);
typedef void           (AI_APIENTRY* PFNGLVERTEX2DPROC)              (GLdouble x, GLdouble y);
typedef void           (AI_APIENTRY* PFNGLVERTEX2DVPROC)             (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX2FPROC)              (GLfloat x, GLfloat y);
typedef void           (AI_APIENTRY* PFNGLVERTEX2FVPROC)             (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX2IPROC)              (GLint x, GLint y);
typedef void           (AI_APIENTRY* PFNGLVERTEX2IVPROC)             (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX2SPROC)              (GLshort x, GLshort y);
typedef void           (AI_APIENTRY* PFNGLVERTEX2SVPROC)             (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX3DPROC)              (GLdouble x, GLdouble y, GLdouble z);
typedef void           (AI_APIENTRY* PFNGLVERTEX3DVPROC)             (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX3FPROC)              (GLfloat x, GLfloat y, GLfloat z);
typedef void           (AI_APIENTRY* PFNGLVERTEX3FVPROC)             (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX3IPROC)              (GLint x, GLint y, GLint z);
typedef void           (AI_APIENTRY* PFNGLVERTEX3IVPROC)             (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX3SPROC)              (GLshort x, GLshort y, GLshort z);
typedef void           (AI_APIENTRY* PFNGLVERTEX3SVPROC)             (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX4DPROC)              (GLdouble x, GLdouble y, GLdouble z, GLdouble w);
typedef void           (AI_APIENTRY* PFNGLVERTEX4DVPROC)             (const GLdouble *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX4FPROC)              (GLfloat x, GLfloat y, GLfloat z, GLfloat w);
typedef void           (AI_APIENTRY* PFNGLVERTEX4FVPROC)             (const GLfloat *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX4IPROC)              (GLint x, GLint y, GLint z, GLint w);
typedef void           (AI_APIENTRY* PFNGLVERTEX4IVPROC)             (const GLint *v);
typedef void           (AI_APIENTRY* PFNGLVERTEX4SPROC)              (GLshort x, GLshort y, GLshort z, GLshort w);
typedef void           (AI_APIENTRY* PFNGLVERTEX4SVPROC)             (const GLshort *v);
typedef void           (AI_APIENTRY* PFNGLVERTEXPOINTERPROC)         (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
typedef void           (AI_APIENTRY* PFNGLVIEWPORTPROC)              (GLint x, GLint y, GLsizei width, GLsizei height);

/* GL_EXT_texture_object */
#define GL_TEXTURE_PRIORITY_EXT   (0x8066)
#define GL_TEXTURE_RESIDENT_EXT   (0x8067)
#define GL_TEXTURE_1D_BINDING_EXT 0x8068
#define GL_TEXTURE_2D_BINDING_EXT 0x8069
#define GL_TEXTURE_3D_BINDING_EXT 0x806A

#endif /* AI_TYPES_TYPEDEFS_H */