/* API Interceptor (c) 2024 Dominik Witczak
 *
 * This code is licensed under MIT license (see LICENSE.txt for details)
 */
#ifndef COMMON_TYPES_H
#define COMMON_TYPES_H

#include "globals.h"
#include "Common/macros.h"
#include <cstdint>
#include <vector>

namespace APIInterceptor
{
    enum APIFunction : uint32_t
    {
        /* GDI32 */
        APIFUNCTION_GDI32_FIRST,
        APIFUNCTION_GDI32_CHOOSEPIXELFORMAT = APIFUNCTION_GDI32_FIRST,
        APIFUNCTION_GDI32_DESCRIBEPIXELFORMAT,
        APIFUNCTION_GDI32_GETPIXELFORMAT,
        APIFUNCTION_GDI32_SETPIXELFORMAT,
        APIFUNCTION_GDI32_SWAPBUFFERS,
        APIFUNCTION_GDI32_LAST              = APIFUNCTION_GDI32_SWAPBUFFERS,

        /* OpenGL */
        APIFUNCTION_GL_FIRST,
        APIFUNCTION_GL_GLACCUM          = APIFUNCTION_GL_FIRST,
        APIFUNCTION_GL_GLACTIVETEXTURE,
        APIFUNCTION_GL_GLALPHAFUNC,
        APIFUNCTION_GL_GLARETEXTURESRESIDENT,
        APIFUNCTION_GL_GLARRAYELEMENT,
        APIFUNCTION_GL_GLATTACHSHADER,
        APIFUNCTION_GL_GLBEGIN,
        APIFUNCTION_GL_GLBEGINCONDITIONALRENDER,
        APIFUNCTION_GL_GLBEGINQUERY,
        APIFUNCTION_GL_GLBEGINTRANSFORMFEEDBACK,
        APIFUNCTION_GL_GLBINDATTRIBLOCATION,
        APIFUNCTION_GL_GLBINDBUFFER,
        APIFUNCTION_GL_GLBINDBUFFERBASE,
        APIFUNCTION_GL_GLBINDBUFFERRANGE,
        APIFUNCTION_GL_GLBINDFRAGDATALOCATION,
        APIFUNCTION_GL_GLBINDFRAMEBUFFER,
        APIFUNCTION_GL_GLBINDRENDERBUFFER,
        APIFUNCTION_GL_GLBINDTEXTURE,
        APIFUNCTION_GL_GLBINDVERTEXARRAY,
        APIFUNCTION_GL_GLBITMAP,
        APIFUNCTION_GL_GLBLENDCOLOR,
        APIFUNCTION_GL_GLBLENDEQUATION,
        APIFUNCTION_GL_GLBLENDEQUATIONSEPARATE,
        APIFUNCTION_GL_GLBLENDFUNC,
        APIFUNCTION_GL_GLBLENDFUNCSEPARATE,
        APIFUNCTION_GL_GLBLITFRAMEBUFFER,
        APIFUNCTION_GL_GLBUFFERDATA,
        APIFUNCTION_GL_GLBUFFERSUBDATA,
        APIFUNCTION_GL_GLCALLLIST,
        APIFUNCTION_GL_GLCALLLISTS,
        APIFUNCTION_GL_GLCHECKFRAMEBUFFERSTATUS,
        APIFUNCTION_GL_GLCLAMPCOLOR,
        APIFUNCTION_GL_GLCLEAR,
        APIFUNCTION_GL_GLCLEARACCUM,
        APIFUNCTION_GL_GLCLEARBUFFERFI,
        APIFUNCTION_GL_GLCLEARBUFFERFV,
        APIFUNCTION_GL_GLCLEARBUFFERUIV,
        APIFUNCTION_GL_GLCLEARCOLOR,
        APIFUNCTION_GL_GLCLEARDEPTH,
        APIFUNCTION_GL_GLCLEARINDEX,
        APIFUNCTION_GL_GLCLEARSTENCIL,
        APIFUNCTION_GL_GLCLIENTWAITSYNC,
        APIFUNCTION_GL_GLCLIPPLANE,
        APIFUNCTION_GL_GLCOLOR3B,
        APIFUNCTION_GL_GLCOLOR3BV,
        APIFUNCTION_GL_GLCOLOR3D,
        APIFUNCTION_GL_GLCOLOR3DV,
        APIFUNCTION_GL_GLCOLOR3F,
        APIFUNCTION_GL_GLCOLOR3FV,
        APIFUNCTION_GL_GLCOLOR3I,
        APIFUNCTION_GL_GLCOLOR3IV,
        APIFUNCTION_GL_GLCOLOR3S,
        APIFUNCTION_GL_GLCOLOR3SV,
        APIFUNCTION_GL_GLCOLOR3UB,
        APIFUNCTION_GL_GLCOLOR3UBV,
        APIFUNCTION_GL_GLCOLOR3UI,
        APIFUNCTION_GL_GLCOLOR3UIV,
        APIFUNCTION_GL_GLCOLOR3US,
        APIFUNCTION_GL_GLCOLOR3USV,
        APIFUNCTION_GL_GLCOLOR4B,
        APIFUNCTION_GL_GLCOLOR4BV,
        APIFUNCTION_GL_GLCOLOR4D,
        APIFUNCTION_GL_GLCOLOR4DV,
        APIFUNCTION_GL_GLCOLOR4F,
        APIFUNCTION_GL_GLCOLOR4FV,
        APIFUNCTION_GL_GLCOLOR4I,
        APIFUNCTION_GL_GLCOLOR4IV,
        APIFUNCTION_GL_GLCOLOR4S,
        APIFUNCTION_GL_GLCOLOR4SV,
        APIFUNCTION_GL_GLCOLOR4UB,
        APIFUNCTION_GL_GLCOLOR4UBV,
        APIFUNCTION_GL_GLCOLOR4UI,
        APIFUNCTION_GL_GLCOLOR4UIV,
        APIFUNCTION_GL_GLCOLOR4US,
        APIFUNCTION_GL_GLCOLOR4USV,
        APIFUNCTION_GL_GLCOLORMASK,
        APIFUNCTION_GL_GLCOLORMASKI,
        APIFUNCTION_GL_GLCOLORMATERIAL,
        APIFUNCTION_GL_GLCOLORPOINTER,
        APIFUNCTION_GL_GLCOMPILESHADER,
        APIFUNCTION_GL_GLCOMPRESSEDTEXIMAGE1D,
        APIFUNCTION_GL_GLCOMPRESSEDTEXIMAGE2D,
        APIFUNCTION_GL_GLCOMPRESSEDTEXIMAGE3D,
        APIFUNCTION_GL_GLCOMPRESSEDTEXSUBIMAGE1D,
        APIFUNCTION_GL_GLCOMPRESSEDTEXSUBIMAGE2D,
        APIFUNCTION_GL_GLCOMPRESSEDTEXSUBIMAGE3D,
        APIFUNCTION_GL_GLCOPYBUFFERSUBDATA,
        APIFUNCTION_GL_GLCOPYPIXELS,
        APIFUNCTION_GL_GLCOPYTEXIMAGE1D,
        APIFUNCTION_GL_GLCOPYTEXIMAGE2D,
        APIFUNCTION_GL_GLCOPYTEXSUBIMAGE1D,
        APIFUNCTION_GL_GLCOPYTEXSUBIMAGE2D,
        APIFUNCTION_GL_GLCOPYTEXSUBIMAGE3D,
        APIFUNCTION_GL_GLCREATEPROGRAM,
        APIFUNCTION_GL_GLCREATESHADER,
        APIFUNCTION_GL_GLCULLFACE,
        APIFUNCTION_GL_GLDELETEBUFFERS,
        APIFUNCTION_GL_GLDELETEFRAMEBUFFERS,
        APIFUNCTION_GL_GLDELETELISTS,
        APIFUNCTION_GL_GLDELETEPROGRAM,
        APIFUNCTION_GL_GLDELETEQUERIES,
        APIFUNCTION_GL_GLDELETERENDERBUFFERS,
        APIFUNCTION_GL_GLDELETESHADER,
        APIFUNCTION_GL_GLDELETESYNC,
        APIFUNCTION_GL_GLDELETETEXTURES,
        APIFUNCTION_GL_GLDELETEVERTEXARRAYS,
        APIFUNCTION_GL_GLDEPTHFUNC,
        APIFUNCTION_GL_GLDEPTHMASK,
        APIFUNCTION_GL_GLDEPTHRANGE,
        APIFUNCTION_GL_GLDETACHSHADER,
        APIFUNCTION_GL_GLDISABLE,
        APIFUNCTION_GL_GLDISABLECLIENTSTATE,
        APIFUNCTION_GL_GLDISABLEVERTEXATTRIBARRAY,
        APIFUNCTION_GL_GLDISABLEI,
        APIFUNCTION_GL_GLDRAWARRAYS,
        APIFUNCTION_GL_GLDRAWARRAYSINSTANCED,
        APIFUNCTION_GL_GLDRAWBUFFER,
        APIFUNCTION_GL_GLDRAWBUFFERS,
        APIFUNCTION_GL_GLDRAWELEMENTS,
        APIFUNCTION_GL_GLDRAWELEMENTSBASEVERTEX,
        APIFUNCTION_GL_GLDRAWELEMENTSINSTANCED,
        APIFUNCTION_GL_GLDRAWELEMENTSINSTANCEDBASEVERTEX,
        APIFUNCTION_GL_GLDRAWPIXELS,
        APIFUNCTION_GL_GLDRAWRANGEELEMENTS,
        APIFUNCTION_GL_GLDRAWRANGEELEMENTSBASEVERTEX,
        APIFUNCTION_GL_GLEDGEFLAG,
        APIFUNCTION_GL_GLEDGEFLAGPOINTER,
        APIFUNCTION_GL_GLEDGEFLAGV,
        APIFUNCTION_GL_GLENABLE,
        APIFUNCTION_GL_GLENABLECLIENTSTATE,
        APIFUNCTION_GL_GLENABLEVERTEXATTRIBARRAY,
        APIFUNCTION_GL_GLENABLEI,
        APIFUNCTION_GL_GLEND,
        APIFUNCTION_GL_GLENDCONDITIONALRENDER,
        APIFUNCTION_GL_GLENDLIST,
        APIFUNCTION_GL_GLENDQUERY,
        APIFUNCTION_GL_GLENDTRANSFORMFEEDBACK,
        APIFUNCTION_GL_GLEVALCOORD1D,
        APIFUNCTION_GL_GLEVALCOORD1DV,
        APIFUNCTION_GL_GLEVALCOORD1F,
        APIFUNCTION_GL_GLEVALCOORD1FV,
        APIFUNCTION_GL_GLEVALCOORD2D,
        APIFUNCTION_GL_GLEVALCOORD2DV,
        APIFUNCTION_GL_GLEVALCOORD2F,
        APIFUNCTION_GL_GLEVALCOORD2FV,
        APIFUNCTION_GL_GLEVALMESH1,
        APIFUNCTION_GL_GLEVALMESH2,
        APIFUNCTION_GL_GLEVALPOINT1,
        APIFUNCTION_GL_GLEVALPOINT2,
        APIFUNCTION_GL_GLFEEDBACKBUFFER,
        APIFUNCTION_GL_GLFENCESYNC,
        APIFUNCTION_GL_GLFINISH,
        APIFUNCTION_GL_GLFLUSH,
        APIFUNCTION_GL_GLFLUSHMAPPEDBUFFERRANGE,
        APIFUNCTION_GL_GLFOGF,
        APIFUNCTION_GL_GLFOGFV,
        APIFUNCTION_GL_GLFOGI,
        APIFUNCTION_GL_GLFOGIV,
        APIFUNCTION_GL_GLFRAMEBUFFERRENDERBUFFER,
        APIFUNCTION_GL_GLFRAMEBUFFERTEXTURE,
        APIFUNCTION_GL_GLFRAMEBUFFERTEXTURE1D,
        APIFUNCTION_GL_GLFRAMEBUFFERTEXTURE2D,
        APIFUNCTION_GL_GLFRAMEBUFFERTEXTURE3D,
        APIFUNCTION_GL_GLFRAMEBUFFERTEXTURELAYER,
        APIFUNCTION_GL_GLFRONTFACE,
        APIFUNCTION_GL_GLFRUSTUM,
        APIFUNCTION_GL_GLGENBUFFERS,
        APIFUNCTION_GL_GLGENFRAMEBUFFERS,
        APIFUNCTION_GL_GLGENLISTS,
        APIFUNCTION_GL_GLGENQUERIES,
        APIFUNCTION_GL_GLGENRENDERBUFFERS,
        APIFUNCTION_GL_GLGENTEXTURES,
        APIFUNCTION_GL_GLGENVERTEXARRAYS,
        APIFUNCTION_GL_GLGENERATEMIPMAP,
        APIFUNCTION_GL_GLGETACTIVEATTRIB,
        APIFUNCTION_GL_GLGETACTIVEUNIFORM,
        APIFUNCTION_GL_GLGETACTIVEUNIFORMBLOCKNAME,
        APIFUNCTION_GL_GLGETACTIVEUNIFORMBLOCKIV,
        APIFUNCTION_GL_GLGETACTIVEUNIFORMNAME,
        APIFUNCTION_GL_GLGETACTIVEUNIFORMSIV,
        APIFUNCTION_GL_GLGETATTACHEDSHADERS,
        APIFUNCTION_GL_GLGETATTRIBLOCATION,
        APIFUNCTION_GL_GLGETBOOLEANI_V,
        APIFUNCTION_GL_GLGETBOOLEANV,
        APIFUNCTION_GL_GLGETBUFFERPARAMETERI64V,
        APIFUNCTION_GL_GLGETBUFFERPARAMETERIV,
        APIFUNCTION_GL_GLGETBUFFERPOINTERV,
        APIFUNCTION_GL_GLGETBUFFERSUBDATA,
        APIFUNCTION_GL_GLGETCLIPPLANE,
        APIFUNCTION_GL_GLGETCOMPRESSEDTEXIMAGE,
        APIFUNCTION_GL_GLGETDOUBLEV,
        APIFUNCTION_GL_GLGETERROR,
        APIFUNCTION_GL_GLGETFLOATV,
        APIFUNCTION_GL_GLGETFRAGDATALOCATION,
        APIFUNCTION_GL_GLGETFRAMEBUFFERATTACHMENTPARAMETERIV,
        APIFUNCTION_GL_GLGETINTEGER64I_V,
        APIFUNCTION_GL_GLGETINTEGER64V,
        APIFUNCTION_GL_GLGETINTEGERI_V,
        APIFUNCTION_GL_GLGETINTEGERV,
        APIFUNCTION_GL_GLGETLIGHTFV,
        APIFUNCTION_GL_GLGETLIGHTIV,
        APIFUNCTION_GL_GLGETMAPDV,
        APIFUNCTION_GL_GLGETMAPFV,
        APIFUNCTION_GL_GLGETMAPIV,
        APIFUNCTION_GL_GLGETMATERIALFV,
        APIFUNCTION_GL_GLGETMATERIALIV,
        APIFUNCTION_GL_GLGETMULTISAMPLEFV,
        APIFUNCTION_GL_GLGETPIXELMAPFV,
        APIFUNCTION_GL_GLGETPIXELMAPUIV,
        APIFUNCTION_GL_GLGETPIXELMAPUSV,
        APIFUNCTION_GL_GLGETPOINTERV,
        APIFUNCTION_GL_GLGETPOLYGONSTIPPLE,
        APIFUNCTION_GL_GLGETPROGRAMINFOLOG,
        APIFUNCTION_GL_GLGETPROGRAMIV,
        APIFUNCTION_GL_GLGETQUERYOBJECTIV,
        APIFUNCTION_GL_GLGETQUERYOBJECTUIV,
        APIFUNCTION_GL_GLGETQUERYIV,
        APIFUNCTION_GL_GLGETRENDERBUFFERPARAMETERIV,
        APIFUNCTION_GL_GLGETSHADERINFOLOG,
        APIFUNCTION_GL_GLGETSHADERSOURCE,
        APIFUNCTION_GL_GLGETSHADERIV,
        APIFUNCTION_GL_GLGETSTRING,
        APIFUNCTION_GL_GLGETSTRINGI,
        APIFUNCTION_GL_GLGETSYNCIV,
        APIFUNCTION_GL_GLGETTEXENVFV,
        APIFUNCTION_GL_GLGETTEXENVIV,
        APIFUNCTION_GL_GLGETTEXGENDV,
        APIFUNCTION_GL_GLGETTEXGENIV,
        APIFUNCTION_GL_GLGETTEXIMAGE,
        APIFUNCTION_GL_GLGETTEXLEVELPARAMETERFV,
        APIFUNCTION_GL_GLGETTEXLEVELPARAMETERIV,
        APIFUNCTION_GL_GLGETTEXPARAMETERI_IV,
        APIFUNCTION_GL_GLGETTEXPARAMETERI_UIV,
        APIFUNCTION_GL_GLGETTEXPARAMETERFV,
        APIFUNCTION_GL_GLGETTEXPARAMETERIV,
        APIFUNCTION_GL_GLGETTRANSFORMFEEDBACKVARYING,
        APIFUNCTION_GL_GLGETUNIFORMBLOCKINDEX,
        APIFUNCTION_GL_GLGETUNIFORMINDICES,
        APIFUNCTION_GL_GLGETUNIFORMLOCATION,
        APIFUNCTION_GL_GLGETUNIFORMFV,
        APIFUNCTION_GL_GLGETUNIFORMIV,
        APIFUNCTION_GL_GLGETUNIFORMUIV,
        APIFUNCTION_GL_GLGETVERTEXATTRIBI_IV,
        APIFUNCTION_GL_GLGETVERTEXATTRIBI_UIV,
        APIFUNCTION_GL_GLGETVERTEXATTRIBPOINTERV,
        APIFUNCTION_GL_GLGETVERTEXATTRIBDV,
        APIFUNCTION_GL_GLGETVERTEXATTRIBFV,
        APIFUNCTION_GL_GLGETVERTEXATTRIBIV,
        APIFUNCTION_GL_GLHINT,
        APIFUNCTION_GL_GLINDEXD,
        APIFUNCTION_GL_GLINDEXDV,
        APIFUNCTION_GL_GLINDEXF,
        APIFUNCTION_GL_GLINDEXFV,
        APIFUNCTION_GL_GLINDEXI,
        APIFUNCTION_GL_GLINDEXIV,
        APIFUNCTION_GL_GLINDEXMASK,
        APIFUNCTION_GL_GLINDEXPOINTER,
        APIFUNCTION_GL_GLINDEXS,
        APIFUNCTION_GL_GLINDEXSV,
        APIFUNCTION_GL_GLINDEXUB,
        APIFUNCTION_GL_GLINDEXUBV,
        APIFUNCTION_GL_GLINITNAMES,
        APIFUNCTION_GL_GLINTERLEAVEDARRRAYS,
        APIFUNCTION_GL_GLISBUFFER,
        APIFUNCTION_GL_GLISENABLED,
        APIFUNCTION_GL_GLISENABLEDI,
        APIFUNCTION_GL_GLISFRAMEBUFFER,
        APIFUNCTION_GL_GLISLIST,
        APIFUNCTION_GL_GLISPROGRAM,
        APIFUNCTION_GL_GLISQUERY,
        APIFUNCTION_GL_GLISRENDERBUFFER,
        APIFUNCTION_GL_GLISSHADER,
        APIFUNCTION_GL_GLISSYNC,
        APIFUNCTION_GL_GLISTEXTURE,
        APIFUNCTION_GL_GLISVERTEXARRAY,
        APIFUNCTION_GL_GLLIGHTF,
        APIFUNCTION_GL_GLLIGHTFV,
        APIFUNCTION_GL_GLLIGHTI,
        APIFUNCTION_GL_GLLIGHTIV,
        APIFUNCTION_GL_GLLIGHTMODELF,
        APIFUNCTION_GL_GLLIGHTMODELFV,
        APIFUNCTION_GL_GLLIGHTMODELI,
        APIFUNCTION_GL_GLLIGHTMODELIV,
        APIFUNCTION_GL_GLLINESTIPPLE,
        APIFUNCTION_GL_GLLINEWIDTH,
        APIFUNCTION_GL_GLLINKPROGRAM,
        APIFUNCTION_GL_GLLISTBASE,
        APIFUNCTION_GL_GLLOADIDENTITY,
        APIFUNCTION_GL_GLLOADMATRIXD,
        APIFUNCTION_GL_GLLOADMATRIXF,
        APIFUNCTION_GL_GLLOADNAME,
        APIFUNCTION_GL_GLLOGICOP,
        APIFUNCTION_GL_GLMAP1D,
        APIFUNCTION_GL_GLMAP1F,
        APIFUNCTION_GL_GLMAP2D,
        APIFUNCTION_GL_GLMAP2F,
        APIFUNCTION_GL_GLMAPGRID1D,
        APIFUNCTION_GL_GLMAPGRID1F,
        APIFUNCTION_GL_GLMAPGRID2D,
        APIFUNCTION_GL_GLMAPGRID2F,
        APIFUNCTION_GL_GLMATERIALF,
        APIFUNCTION_GL_GLMATERIALFV,
        APIFUNCTION_GL_GLMATERIALI,
        APIFUNCTION_GL_GLMATERIALIV,
        APIFUNCTION_GL_GLMATRIXMODE,
        APIFUNCTION_GL_GLMULTMATRIXD,
        APIFUNCTION_GL_GLMULTMATRIXF,
        APIFUNCTION_GL_GLMULTIDRAWARRAYS,
        APIFUNCTION_GL_GLMULTIDRAWELEMENTS,
        APIFUNCTION_GL_GLMULTIDRAWELEMENTSBASEVERTEX,
        APIFUNCTION_GL_GLNEWLIST,
        APIFUNCTION_GL_GLNORMAL3B,
        APIFUNCTION_GL_GLNORMAL3BV,
        APIFUNCTION_GL_GLNORMAL3D,
        APIFUNCTION_GL_GLNORMAL3DV,
        APIFUNCTION_GL_GLNORMAL3F,
        APIFUNCTION_GL_GLNORMAL3FV,
        APIFUNCTION_GL_GLNORMAL3I,
        APIFUNCTION_GL_GLNORMAL3IV,
        APIFUNCTION_GL_GLNORMAL3S,
        APIFUNCTION_GL_GLNORMAL3SV,
        APIFUNCTION_GL_GLNORMALPOINTER,
        APIFUNCTION_GL_GLORTHO,
        APIFUNCTION_GL_GLPASSTHROUGH,
        APIFUNCTION_GL_GLPIXELMAPFV,
        APIFUNCTION_GL_GLPIXELMAPUIV,
        APIFUNCTION_GL_GLPIXELMAPUSV,
        APIFUNCTION_GL_GLPIXELSTOREF,
        APIFUNCTION_GL_GLPIXELSTOREI,
        APIFUNCTION_GL_GLPIXELTRANSFERF,
        APIFUNCTION_GL_GLPIXELTRANSFERI,
        APIFUNCTION_GL_GLPIXELZOOM,
        APIFUNCTION_GL_GLPOINTPARAMETERF,
        APIFUNCTION_GL_GLPOINTPARAMETERFV,
        APIFUNCTION_GL_GLPOINTPARAMETERI,
        APIFUNCTION_GL_GLPOINTPARAMETERIV,
        APIFUNCTION_GL_GLPOINTSIZE,
        APIFUNCTION_GL_GLPOLYGONMODE,
        APIFUNCTION_GL_GLPOLYGONOFFSET,
        APIFUNCTION_GL_GLPOLYGONSTIPPLE,
        APIFUNCTION_GL_GLPOPATTRIB,
        APIFUNCTION_GL_GLPOPCLIENTATTRIB,
        APIFUNCTION_GL_GLPOPMATRIX,
        APIFUNCTION_GL_GLPOPNAME,
        APIFUNCTION_GL_GLPRIMITIVERESTARTINDEX,
        APIFUNCTION_GL_GLPRIORITIZETEXTURES,
        APIFUNCTION_GL_GLPROVOKINGVERTEX,
        APIFUNCTION_GL_GLPUSHATTRIB,
        APIFUNCTION_GL_GLPUSHCLIENTATTRIB,
        APIFUNCTION_GL_GLPUSHMATRIX,
        APIFUNCTION_GL_GLPUSHNAME,
        APIFUNCTION_GL_GLRASTERPOS2D,
        APIFUNCTION_GL_GLRASTERPOS2DV,
        APIFUNCTION_GL_GLRASTERPOS2F,
        APIFUNCTION_GL_GLRASTERPOS2FV,
        APIFUNCTION_GL_GLRASTERPOS2I,
        APIFUNCTION_GL_GLRASTERPOS2IV,
        APIFUNCTION_GL_GLRASTERPOS2S,
        APIFUNCTION_GL_GLRASTERPOS2SV,
        APIFUNCTION_GL_GLRASTERPOS3D,
        APIFUNCTION_GL_GLRASTERPOS3DV,
        APIFUNCTION_GL_GLRASTERPOS3F,
        APIFUNCTION_GL_GLRASTERPOS3FV,
        APIFUNCTION_GL_GLRASTERPOS3I,
        APIFUNCTION_GL_GLRASTERPOS3IV,
        APIFUNCTION_GL_GLRASTERPOS3S,
        APIFUNCTION_GL_GLRASTERPOS3SV,
        APIFUNCTION_GL_GLRASTERPOS4D,
        APIFUNCTION_GL_GLRASTERPOS4DV,
        APIFUNCTION_GL_GLRASTERPOS4F,
        APIFUNCTION_GL_GLRASTERPOS4FV,
        APIFUNCTION_GL_GLRASTERPOS4I,
        APIFUNCTION_GL_GLRASTERPOS4IV,
        APIFUNCTION_GL_GLRASTERPOS4S,
        APIFUNCTION_GL_GLRASTERPOS4SV,
        APIFUNCTION_GL_GLREADBUFFER,
        APIFUNCTION_GL_GLREADPIXELS,
        APIFUNCTION_GL_GLRECTD,
        APIFUNCTION_GL_GLRECTDV,
        APIFUNCTION_GL_GLRECTF,
        APIFUNCTION_GL_GLRECTFV,
        APIFUNCTION_GL_GLRECTI,
        APIFUNCTION_GL_GLRECTIV,
        APIFUNCTION_GL_GLRECTS,
        APIFUNCTION_GL_GLRECTSV,
        APIFUNCTION_GL_GLRENDERMODE,
        APIFUNCTION_GL_GLRENDERBUFFERSTORAGE,
        APIFUNCTION_GL_GLRENDERBUFFERSTORAGEMULTISAMPLE,
        APIFUNCTION_GL_GLROTATED,
        APIFUNCTION_GL_GLROTATEF,
        APIFUNCTION_GL_GLSAMPLECOVERAGE,
        APIFUNCTION_GL_GLSAMPLEMASKI,
        APIFUNCTION_GL_GLSCALED,
        APIFUNCTION_GL_GLSCALEF,
        APIFUNCTION_GL_GLSCISSOR,
        APIFUNCTION_GL_GLSELECTBUFFER,
        APIFUNCTION_GL_GLSHADEMODEL,
        APIFUNCTION_GL_GLSHADERSOURCE,
        APIFUNCTION_GL_GLSTENCILFUNC,
        APIFUNCTION_GL_GLSTENCILMASK,
        APIFUNCTION_GL_GLSTENCILMASKSEPARATE,
        APIFUNCTION_GL_GLSTENCILOP,
        APIFUNCTION_GL_GLSTENCILOPSEPARATE,
        APIFUNCTION_GL_GLTEXBUFFER,
        APIFUNCTION_GL_GLTEXCOORD1D,
        APIFUNCTION_GL_GLTEXCOORD1DV,
        APIFUNCTION_GL_GLTEXCOORD1F,
        APIFUNCTION_GL_GLTEXCOORD1FV,
        APIFUNCTION_GL_GLTEXCOORD1I,
        APIFUNCTION_GL_GLTEXCOORD1IV,
        APIFUNCTION_GL_GLTEXCOORD1S,
        APIFUNCTION_GL_GLTEXCOORD1SV,
        APIFUNCTION_GL_GLTEXCOORD2D,
        APIFUNCTION_GL_GLTEXCOORD2DV,
        APIFUNCTION_GL_GLTEXCOORD2F,
        APIFUNCTION_GL_GLTEXCOORD2FV,
        APIFUNCTION_GL_GLTEXCOORD2I,
        APIFUNCTION_GL_GLTEXCOORD2IV,
        APIFUNCTION_GL_GLTEXCOORD2S,
        APIFUNCTION_GL_GLTEXCOORD2SV,
        APIFUNCTION_GL_GLTEXCOORD3D,
        APIFUNCTION_GL_GLTEXCOORD3DV,
        APIFUNCTION_GL_GLTEXCOORD3F,
        APIFUNCTION_GL_GLTEXCOORD3FV,
        APIFUNCTION_GL_GLTEXCOORD3I,
        APIFUNCTION_GL_GLTEXCOORD3IV,
        APIFUNCTION_GL_GLTEXCOORD3S,
        APIFUNCTION_GL_GLTEXCOORD3SV,
        APIFUNCTION_GL_GLTEXCOORD4D,
        APIFUNCTION_GL_GLTEXCOORD4DV,
        APIFUNCTION_GL_GLTEXCOORD4F,
        APIFUNCTION_GL_GLTEXCOORD4FV,
        APIFUNCTION_GL_GLTEXCOORD4I,
        APIFUNCTION_GL_GLTEXCOORD4IV,
        APIFUNCTION_GL_GLTEXCOORD4S,
        APIFUNCTION_GL_GLTEXCOORD4SV,
        APIFUNCTION_GL_GLTEXCOORDPOINTER,
        APIFUNCTION_GL_GLTEXENVF,
        APIFUNCTION_GL_GLTEXENVFV,
        APIFUNCTION_GL_GLTEXENVI,
        APIFUNCTION_GL_GLTEXENVIV,
        APIFUNCTION_GL_GLTEXGEND,
        APIFUNCTION_GL_GLTEXGENDV,
        APIFUNCTION_GL_GLTEXGENI,
        APIFUNCTION_GL_GLTEXGENIV,
        APIFUNCTION_GL_GLTEXIMAGE1D,
        APIFUNCTION_GL_GLTEXIMAGE2D,
        APIFUNCTION_GL_GLTEXIMAGE2DMULTISMAPLE,
        APIFUNCTION_GL_GLTEXIMAGE3D,
        APIFUNCTION_GL_GLTEXIMAGE3DMULTISMAPLE,
        APIFUNCTION_GL_GLTEXPARAMETERI_IV,
        APIFUNCTION_GL_GLTEXPARAMETERI_IUIV,
        APIFUNCTION_GL_GLTEXPARAMETERF,
        APIFUNCTION_GL_GLTEXPARAMETERFV,
        APIFUNCTION_GL_GLTEXPARAMETERI,
        APIFUNCTION_GL_GLTEXPARAMETERIV,
        APIFUNCTION_GL_GLTEXSUBIMAGE1D,
        APIFUNCTION_GL_GLTEXSUBIMAGE2D,
        APIFUNCTION_GL_GLTEXSUBIMAGE3D,
        APIFUNCTION_GL_GLTRANSFORMFEEDBACKVARYINGS,
        APIFUNCTION_GL_GLTRANSLATED,
        APIFUNCTION_GL_GLTRANSLATEF,
        APIFUNCTION_GL_GLUNIFORM1F,
        APIFUNCTION_GL_GLUNIFORM1FV,
        APIFUNCTION_GL_GLUNIFORM1I,
        APIFUNCTION_GL_GLUNIFORM1IV,
        APIFUNCTION_GL_GLUNIFORM1UI,
        APIFUNCTION_GL_GLUNIFORM1UIV,
        APIFUNCTION_GL_GLUNIFORM2F,
        APIFUNCTION_GL_GLUNIFORM2FV,
        APIFUNCTION_GL_GLUNIFORM2I,
        APIFUNCTION_GL_GLUNIFORM2IV,
        APIFUNCTION_GL_GLUNIFORM2UI,
        APIFUNCTION_GL_GLUNIFORM2UIV,
        APIFUNCTION_GL_GLUNIFORM3F,
        APIFUNCTION_GL_GLUNIFORM3FV,
        APIFUNCTION_GL_GLUNIFORM3I,
        APIFUNCTION_GL_GLUNIFORM3IV,
        APIFUNCTION_GL_GLUNIFORM3UI,
        APIFUNCTION_GL_GLUNIFORM3UIV,
        APIFUNCTION_GL_GLUNIFORM4F,
        APIFUNCTION_GL_GLUNIFORM4FV,
        APIFUNCTION_GL_GLUNIFORM4I,
        APIFUNCTION_GL_GLUNIFORM4IV,
        APIFUNCTION_GL_GLUNIFORM4UI,
        APIFUNCTION_GL_GLUNIFORM4UIV,
        APIFUNCTION_GL_GLUNIFORMBLOCKBINDING,
        APIFUNCTION_GL_GLUNIFORMMATRIX2FV,
        APIFUNCTION_GL_GLUNIFORMMATRIX2X3FV,
        APIFUNCTION_GL_GLUNIFORMMATRIX2X4FV,
        APIFUNCTION_GL_GLUNIFORMMATRIX3FV,
        APIFUNCTION_GL_GLUNIFORMMATRIX3X2FV,
        APIFUNCTION_GL_GLUNIFORMMATRIX3X4FV,
        APIFUNCTION_GL_GLUNIFORMMATRIX4FV,
        APIFUNCTION_GL_GLUNIFORMMATRIX4X2FV,
        APIFUNCTION_GL_GLUNIFORMMATRIX4X3FV,
        APIFUNCTION_GL_GLUNMAPBUFFER,
        APIFUNCTION_GL_GLUSEPROGRAM,
        APIFUNCTION_GL_GLVALIDATEPROGRAM,
        APIFUNCTION_GL_GLVERTEX2D,
        APIFUNCTION_GL_GLVERTEX2DV,
        APIFUNCTION_GL_GLVERTEX2F,
        APIFUNCTION_GL_GLVERTEX2FV,
        APIFUNCTION_GL_GLVERTEX2I,
        APIFUNCTION_GL_GLVERTEX2IV,
        APIFUNCTION_GL_GLVERTEX2S,
        APIFUNCTION_GL_GLVERTEX2SV,
        APIFUNCTION_GL_GLVERTEX3D,
        APIFUNCTION_GL_GLVERTEX3DV,
        APIFUNCTION_GL_GLVERTEX3F,
        APIFUNCTION_GL_GLVERTEX3FV,
        APIFUNCTION_GL_GLVERTEX3I,
        APIFUNCTION_GL_GLVERTEX3IV,
        APIFUNCTION_GL_GLVERTEX3S,
        APIFUNCTION_GL_GLVERTEX3SV,
        APIFUNCTION_GL_GLVERTEX4D,
        APIFUNCTION_GL_GLVERTEX4DV,
        APIFUNCTION_GL_GLVERTEX4F,
        APIFUNCTION_GL_GLVERTEX4FV,
        APIFUNCTION_GL_GLVERTEX4I,
        APIFUNCTION_GL_GLVERTEX4IV,
        APIFUNCTION_GL_GLVERTEX4S,
        APIFUNCTION_GL_GLVERTEX4SV,
        APIFUNCTION_GL_GLVERTEXATTRIB1D,
        APIFUNCTION_GL_GLVERTEXATTRIB1DV,
        APIFUNCTION_GL_GLVERTEXATTRIB1F,
        APIFUNCTION_GL_GLVERTEXATTRIB1FV,
        APIFUNCTION_GL_GLVERTEXATTRIB1S,
        APIFUNCTION_GL_GLVERTEXATTRIB1SV,
        APIFUNCTION_GL_GLVERTEXATTRIB2D,
        APIFUNCTION_GL_GLVERTEXATTRIB2DV,
        APIFUNCTION_GL_GLVERTEXATTRIB2F,
        APIFUNCTION_GL_GLVERTEXATTRIB2FV,
        APIFUNCTION_GL_GLVERTEXATTRIB2S,
        APIFUNCTION_GL_GLVERTEXATTRIB2SV,
        APIFUNCTION_GL_GLVERTEXATTRIB3D,
        APIFUNCTION_GL_GLVERTEXATTRIB3DV,
        APIFUNCTION_GL_GLVERTEXATTRIB3F,
        APIFUNCTION_GL_GLVERTEXATTRIB3FV,
        APIFUNCTION_GL_GLVERTEXATTRIB3S,
        APIFUNCTION_GL_GLVERTEXATTRIB3SV,
        APIFUNCTION_GL_GLVERTEXATTRIB4BV,
        APIFUNCTION_GL_GLVERTEXATTRIB4D,
        APIFUNCTION_GL_GLVERTEXATTRIB4DV,
        APIFUNCTION_GL_GLVERTEXATTRIB4F,
        APIFUNCTION_GL_GLVERTEXATTRIB4FV,
        APIFUNCTION_GL_GLVERTEXATTRIB4S,
        APIFUNCTION_GL_GLVERTEXATTRIB4SV,
        APIFUNCTION_GL_GLVERTEXATTRIB4UBV,
        APIFUNCTION_GL_GLVERTEXATTRIB4UIV,
        APIFUNCTION_GL_GLVERTEXATTRIB4USV,
        APIFUNCTION_GL_GLVERTEXATTRIB4NBV,
        APIFUNCTION_GL_GLVERTEXATTRIB4NIV,
        APIFUNCTION_GL_GLVERTEXATTRIB4NSV,
        APIFUNCTION_GL_GLVERTEXATTRIB4NUB,
        APIFUNCTION_GL_GLVERTEXATTRIB4NUBV,
        APIFUNCTION_GL_GLVERTEXATTRIB4NUIV,
        APIFUNCTION_GL_GLVERTEXATTRIB4NUSV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I1I,
        APIFUNCTION_GL_GLVERTEXATTRIB_I1IV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I1UI,
        APIFUNCTION_GL_GLVERTEXATTRIB_I1UIV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I2I,
        APIFUNCTION_GL_GLVERTEXATTRIB_I2IV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I2UI,
        APIFUNCTION_GL_GLVERTEXATTRIB_I2UIV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I3I,
        APIFUNCTION_GL_GLVERTEXATTRIB_I3IV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I3UI,
        APIFUNCTION_GL_GLVERTEXATTRIB_I3UIV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I4BV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I4I,
        APIFUNCTION_GL_GLVERTEXATTRIB_I4IV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I4SV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I4UBV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I4UI,
        APIFUNCTION_GL_GLVERTEXATTRIB_I4UIV,
        APIFUNCTION_GL_GLVERTEXATTRIB_I4USV,
        APIFUNCTION_GL_GLVERTEXATTRIB_IPOINTER,
        APIFUNCTION_GL_GLVERTEXATTRIBPOINTER,
        APIFUNCTION_GL_GLVERTEXPOINTER,
        APIFUNCTION_GL_GLVIEWPORT,
        APIFUNCTION_GL_GLWAITSYNC,
        APIFUNCTION_GL_LAST             = APIFUNCTION_GL_GLWAITSYNC,

        /* WGL */
        APIFUNCTION_WGL_FIRST,
        APIFUNCTION_WGL_WGLCOPYCONTEXT   = APIFUNCTION_WGL_FIRST,
        APIFUNCTION_WGL_WGLCREATECONTEXT,
        APIFUNCTION_WGL_WGLCREATECONTEXTATTRIBSARB,
        APIFUNCTION_WGL_WGLCREATELAYERCONTEXT,
        APIFUNCTION_WGL_WGLDELETECONTEXT,
        APIFUNCTION_WGL_WGLGETCURRENTCONTEXT,
        APIFUNCTION_WGL_WGLGETCURRENTDC,
        APIFUNCTION_WGL_WGLGETEXTENSIONSSTRINGARB,
        APIFUNCTION_WGL_WGLGETSWAPINTERVALEXT,
        APIFUNCTION_WGL_WGLMAKECURRENT,
        APIFUNCTION_WGL_WGLSHARELISTS,
        APIFUNCTION_WGL_WGLSWAPINTERVALEXT,
        APIFUNCTION_WGL_WGLSWAPLAYERBUFFERS,
        APIFUNCTION_WGL_LAST = APIFUNCTION_WGL_WGLSWAPLAYERBUFFERS,

        /* User32 */
        APIFUNCTION_USER32_FIRST,
        APIFUNCTION_USER32_CREATEWINDOWEXA = APIFUNCTION_USER32_FIRST,
        APIFUNCTION_USER32_LAST = APIFUNCTION_USER32_CREATEWINDOWEXA,

        /* Always last */
        APIFUNCTION_COUNT,
        APIFUNCTION_UNKNOWN = APIFUNCTION_COUNT
    };

    enum APIFunctionArgumentType : uint8_t
    {
        ARGTYPE_F32,
        ARGTYPE_F32_PTR,
        ARGTYPE_F64,
        ARGTYPE_F64_PTR,
        ARGTYPE_I8,
        ARGTYPE_I8_PTR,
        ARGTYPE_I16,
        ARGTYPE_I16_PTR,
        ARGTYPE_I32,
        ARGTYPE_I32_PTR,
        ARGTYPE_U8,
        ARGTYPE_U8_PTR,
        ARGTYPE_U16,
        ARGTYPE_U16_PTR,
        ARGTYPE_U32,
        ARGTYPE_U32_PTR,
        ARGTYPE_VOID_PTR,

        ARGTYPE_DATA_CHUNK_ID,

        UNKNOWN
    };

    typedef uint32_t DataChunkID;

    typedef struct APIFunctionArgument
    {
        APIFunctionArgumentType type;

        static APIFunctionArgument create_data_chunk_id(const DataChunkID& in_id)
        {
            APIFunctionArgument result;

            result.type                      = ARGTYPE_DATA_CHUNK_ID;
            result.value.value_id = in_id;

            return result;
        }

        static APIFunctionArgument create_fp32(const float& in_value)
        {
            APIFunctionArgument result;

            result.type             = ARGTYPE_F32;
            result.value.value_fp32 = in_value;

            return result;
        }

        static APIFunctionArgument create_fp32_ptr(const float* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_F32_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        static APIFunctionArgument create_fp64(const double& in_value)
        {
            APIFunctionArgument result;

            result.type             = ARGTYPE_F64;
            result.value.value_fp64 = in_value;

            return result;
        }

        static APIFunctionArgument create_fp64_ptr(const double* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_F64_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        static APIFunctionArgument create_i8(const char& in_value)
        {
            APIFunctionArgument result;

            result.type           = ARGTYPE_I8;
            result.value.value_i8 = in_value;

            return result;
        }

        static APIFunctionArgument create_i8_ptr(const char* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_I8_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        static APIFunctionArgument create_i16(const short& in_value)
        {
            APIFunctionArgument result;

            result.type            = ARGTYPE_I16;
            result.value.value_i16 = in_value;

            return result;
        }

        static APIFunctionArgument create_i16_ptr(const short* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_I16_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        static APIFunctionArgument create_i32(const int& in_value)
        {
            APIFunctionArgument result;

            result.type            = ARGTYPE_I32;
            result.value.value_i32 = in_value;

            return result;
        }

        static APIFunctionArgument create_i32_ptr(const int* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_I32_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        static APIFunctionArgument create_u16(const unsigned short& in_value)
        {
            APIFunctionArgument result;

            result.type            = ARGTYPE_U16;
            result.value.value_u16 = in_value;

            return result;
        }

        static APIFunctionArgument create_u16_ptr(const unsigned short* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_U16_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        static APIFunctionArgument create_u32(const unsigned int& in_value)
        {
            APIFunctionArgument result;

            result.type            = ARGTYPE_U32;
            result.value.value_u32 = in_value;

            return result;
        }

        static APIFunctionArgument create_u32_ptr(const unsigned int* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_U32_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        static APIFunctionArgument create_u8(const unsigned char& in_value)
        {
            APIFunctionArgument result;

            result.type           = ARGTYPE_U8;
            result.value.value_u8 = in_value;

            return result;
        }

        static APIFunctionArgument create_u8_ptr(const unsigned char* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_U8_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        static APIFunctionArgument create_void_ptr(const void* in_value_ptr)
        {
            APIFunctionArgument result;

            result.type = ARGTYPE_VOID_PTR;

            result.set_ptr_internal(in_value_ptr);
            return result;
        }

        const DataChunkID&    get_data_chunk_id() const;
        const float&          get_fp32         () const;
        const float*          get_fp32_ptr     () const;
        const double&         get_fp64         () const;
        const double*         get_fp64_ptr     () const;
        const char&           get_i8           () const;
        const char*           get_i8_ptr       () const;
        const short&          get_i16          () const;
        const short*          get_i16_ptr      () const;
        const int&            get_i32          () const;
        const int*            get_i32_ptr      () const;
        const unsigned char&  get_u8           () const;
        const unsigned char*  get_u8_ptr       () const;
        const unsigned short& get_u16          () const;
        const unsigned short* get_u16_ptr      () const;
        const unsigned int&   get_u32          () const;
        const unsigned int*   get_u32_ptr      () const;
        const void*           get_ptr          () const;

        const void* get_value_ptr() const
        {
            return &value;
        }

        uint32_t deserialize_from_u8_ptr(const uint8_t*        in_u8_ptr);
        void     serialize_to_u8_vec    (std::vector<uint8_t>* inout_u8_vec_ptr) const;

        APIFunctionArgument()
            :type(UNKNOWN)
        {
            /* Stub */
        }

        APIFunctionArgument(const APIFunctionArgument& in_arg) = default;

    private:

        union
        {
            float          value_fp32;
            double         value_fp64;
            char           value_i8;
            short          value_i16;
            int            value_i32;
            DataChunkID    value_id;
            unsigned char  value_u8;
            unsigned short value_u16;
            unsigned int   value_u32;
            uint64_t       value_ptr_as_u64;
        } value;

        uint32_t    get_n_arg_value_bytes()                   const;
        const void* get_ptr_internal     ()                   const;
        void        set_ptr_internal     (const void* in_ptr);

    } APIFunctionArgument;

    struct APICommand
    {
        APIFunction                      api_func;
        std::vector<APIFunctionArgument> api_arg_vec;

        APICommand()
            :api_func(APIInterceptor::APIFUNCTION_UNKNOWN)
        {
            /* Stub */
        }
    };

    struct FunctionInterceptor
    {
        void** pfn_func_to_intercept_ptr_ptr;
        void*  pfn_interceptor_func_ptr;

        FunctionInterceptor()
        {
            pfn_func_to_intercept_ptr_ptr = nullptr;
            pfn_interceptor_func_ptr      = nullptr;
        }

        FunctionInterceptor(void** in_pfn_func_to_intercept_ptr_ptr,
                            void*  in_pfn_interceptor_func_ptr)
        {
            pfn_func_to_intercept_ptr_ptr = in_pfn_func_to_intercept_ptr_ptr;
            pfn_interceptor_func_ptr      = in_pfn_interceptor_func_ptr;
        }
    };
}

#endif /* COMMON_TYPES_H */